import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
import { siteConfig } from "@/config/site";

export const metadata: Metadata = {
  title: "هیپ‌فوم",
  description: "تولید‌کننده پیشرو در راهکارهای بسته‌بندی پلی‌اتیلن",
  creator: "هیپ‌فوم",
  publisher: "هیپ‌فوم",
  applicationName: "هیپ‌فوم",

  openGraph: {
    title: "هیپ‌فوم",
    description: "تولید‌کننده پیشرو در راهکارهای بسته‌بندی پلی‌اتیلن",
    url: `https://${siteConfig.domain}`,
    siteName: "هیپ‌فوم",
    images: [
      {
        secureUrl: `https://${siteConfig.domain}/socials/og.jpg`,
        url: `https://${siteConfig.domain}/socials/og.jpg`,
        width: 1200,
        height: 630,
        alt: "هیپ‌فوم",
      },
    ],
    locale: "fa-IR",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "هیپ‌فوم",
    description: "تولید‌کننده پیشرو در راهکارهای بسته‌بندی پلی‌اتیلن",
    creator: "@hipfoam",
    images: [`https://${siteConfig.domain}/socials/twitter.jpg`],
  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
